title: Shafiul Ajam Opee
logo: opeepic/opeeimg.JPEG
description: Software Engineer (AI/ML)
email: opee.cse@gmail.com
github_username: Opee10
linkedin_username: shafiul-opee
google_scholar_url: https://scholar.google.com/citations?user=EB3lpmUAAAAJ&hl=en
location: Dhaka, Bangladesh
theme: jekyll-theme-minimal
